export const crops = [
  {
    name: 'No Crop',
    growth: 0,
    compost: 0,
    manure: 0,
    seasons: [],
    icon: '/crop_icons/empty.png',
  },
  {
    name: 'Toma Root',
    growth: -2,
    compost: -2,
    manure: 4,
    seasons: ['Autumn', 'Spring', 'Summer'],
    icon: '/crop_icons/tomaroot.png',
  },
  {
    name: 'Eggplant',
    growth: 2,
    compost: 2,
    manure: -4,
    seasons: ['Autumn', 'Spring'],
    icon: '/crop_icons/eggplant.png',
  },
  {
    name: 'Potato',
    growth: 2,
    compost: 2,
    manure: -4,
    seasons: ['Autumn', 'Winter', 'Spring'],
    icon: '/crop_icons/potato.png',
  },
  {
    name: 'Dragonfruit',
    growth: 4,
    compost: 4,
    manure: -8,
    seasons: ['Spring', 'Summer'],
    icon: '/crop_icons/dragonfruit.png',
  },
  {
    name: 'Pepper',
    growth: 4,
    compost: 4,
    manure: -8,
    seasons: ['Autumn', 'Summer'],
    icon: '/crop_icons/pepper.png',
  },
  {
    name: 'Carrot',
    growth: -4,
    compost: 2,
    manure: 2,
    seasons: ['Autumn', 'Winter', 'Spring'],
    icon: '/crop_icons/carrot.png',
  },
  {
    name: 'Pumpkin',
    growth: -4,
    compost: 2,
    manure: 2,
    seasons: ['Autumn', 'Winter'],
    icon: '/crop_icons/pumpkin.png',
  },
  {
    name: 'Onion',
    growth: -8,
    compost: 4,
    manure: 4,
    seasons: ['Autumn', 'Spring', 'Summer'],
    icon: '/crop_icons/onion.png',
  },
  {
    name: 'Pomegranate',
    growth: -8,
    compost: 4,
    manure: 4,
    seasons: ['Spring', 'Summer'],
    icon: '/crop_icons/pomegranate.png',
  },
  {
    name: 'Aspargus',
    growth: 2,
    compost: -4,
    manure: 2,
    seasons: ['Winter', 'Spring'],
    icon: '/crop_icons/aspargus.png',
  },
  {
    name: 'Corn',
    growth: 2,
    compost: -4,
    manure: 2,
    seasons: ['Autumn', 'Spring', 'Summer'],
    icon: '/crop_icons/corn.png',
  },
  {
    name: 'Durian',
    growth: 4,
    compost: -8,
    manure: 4,
    seasons: ['Spring'],
    icon: '/crop_icons/durian.png',
  },
  {
    name: 'Garlic',
    growth: 4,
    compost: -8,
    manure: 4,
    seasons: ['Autumn', 'Winter', 'Spring', 'Summer'],
    icon: '/crop_icons/garlic.png',
  },
  {
    name: 'Watermelon',
    growth: 4,
    compost: -2,
    manure: -2,
    seasons: ['Spring', 'Summer'],
    icon: '/crop_icons/watermelon.png',
  },
]

export const exampleCombo = [
  crops[1],
  crops[1],
  crops[1],
  crops[1],
  crops[1],
  crops[1],
  crops[2],
  crops[2],
  crops[2],
  crops[2],
]
